server:
  # port on which api-gateway will run
  port: 8082

spring:
  # application name that will be registered in eureka
  application:
    name: api-gateway
  # the easiest way to enable gateway routing is to enable the DISCOVERY LOCATOR.
  # this makes the spring cloud api gateway automatically map and route http request to a destination microservice
  # provided the request is sent to the microservice using its application-name.
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka