server:
  # port: 0 # Assign port number automatically, useful when multiple instances are to be created
  # get these values as arguments when starting the application
  port: ${PORT:0}

spring:
  application:
    name: user-ws
  devtools:
    restart:
      enabled: true

eureka:
  instance:
    # instance-id has to be unique to register multiple instances of same service in eureka.
    # get these values as arguments when starting the application.
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka