server:
  port: 0 # Assign port number automatically, useful when multiple instances are to be created

spring:
  application:
    name: userservice
  devtools:
    restart:
      enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka